# Define the default model configuration


activation_fcts:
  - "relu"
  - "sigmoid"
  - "softmax"
  - "softplus"
  - "softsign"
  - "tanh"
  - "selu"
  - "elu"
  - "exponential"
activation_pick: "random"

optimizers:
  - "sgd"
  - "rmsprop"
  - "adam"
  - "adadelta"
  - "adagrad"
  - "adamax"
  - "nadam"
  - "ftrl"
optimizer_pick: "random"

losses:
  - "mae"
  - "mape"
  - "mse"
  - "msle"
  - "poisson"
  - "categorical_crossentropy"
loss_pick: "random"

hidden_layers_num_lower: 5
hidden_layers_num_upper: 101
hidden_layer_size_lower: 1
hidden_layer_size_upper: 1001


epochs: 10
truncate_from: 2
trials: 5
batch_sizes: [2, 4, 8, 16, 32, 64, 128, 256]
batch_sizes_pick: "random"
input_dim_lower: 1
input_dim_upper: 1001
input_dim_strategy: "same"
